### ISSUE TITLE
Does not work for node >=0.10

### ISSUE THREAD

**Issue by sysrun** [joeferner/node-rtlsdr#2]
pi@sdrpi ~/node-sdr/node_modules/rtlsdr/test $ node rtlsdrTest.js 

/home/pi/node-sdr/node_modules/rtlsdr/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Symbol nodeRtlsdr_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/pi/node-sdr/node_modules/rtlsdr/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/pi/node-sdr/node_modules/rtlsdr/rtlsdr.js:5:41)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by pminervini** [comment]
in binding.cpp:
replace "NODE_MODULE(rtlsdr, init);" with "NODE_MODULE(nodeRtlsdr, init);"
