### ISSUE TITLE
node-rtlsdr doesn't install on version >= 0.12

### ISSUE THREAD

**Issue by jimcondon** [joeferner/node-rtlsdr#5]
It appears this is not compatible with node 0.12. Are there any plans for updating it? Installing on node version v0.12.7, I get:

```
jim@dbr2:~/rtlsdr-nodejs$ sudo npm install node-rtlsdr
/
> rtlsdr@0.0.1 install /home/jim/rtlsdr-nodejs/node_modules/rtlsdr
> node-gyp configure build

make: Entering directory `/home/jim/rtlsdr-nodejs/node_modules/rtlsdr/build'
  CXX(target) Release/obj.target/nodeRtlsdr/src/binding.o
In file included from ../src/binding.cpp:2:0:
../src/nodeRtlSdr.h:6:40: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 v8::Handle<v8::Value> GetDevices(const v8::Arguments& args);
                                        ^
../src/nodeRtlSdr.h:6:55: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 v8::Handle<v8::Value> GetDevices(const v8::Arguments& args);
                                                       ^
In file included from /home/jim/.node-gyp/0.12.7/src/node.h:61:0,
                 from ../src/nodeRtlSdr.h:2,
                 from ../src/binding.cpp:2:
/home/jim/.node-gyp/0.12.7/deps/v8/include/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/home/jim/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/binding.cpp:7:21: error: within this context
     v8::HandleScope scope;
                     ^
../src/binding.cpp:8:53: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [11], v8::Handle<v8::Value> (&)(const int&))’
     NODE_SET_METHOD(target, "getDevices", GetDevices);
                                                     ^
../src/binding.cpp:8:53: note: candidate is:
In file included from ../src/nodeRtlSdr.h:2:0,
                 from ../src/binding.cpp:2:
/home/jim/.node-gyp/0.12.7/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/jim/.node-gyp/0.12.7/src/node.h:228:13: note:   template argument deduction/substitution failed:
../src/binding.cpp:8:53: note:   cannot convert ‘GetDevices’ (type ‘v8::Handle<v8::Value>(const int&)’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackIn$
o<v8::Value>&)}’
     NODE_SET_METHOD(target, "getDevices", GetDevices);
                                                     ^
make: *** [Release/obj.target/nodeRtlsdr/src/binding.o] Error 1
make: Leaving directory `/home/jim/rtlsdr-nodejs/node_modules/rtlsdr/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/jim/rtlsdr-nodejs/node_modules/rtlsdr
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-rtlsdr"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! rtlsdr@0.0.1 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rtlsdr@0.0.1 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the rtlsdr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls rtlsdr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jim/rtlsdr-nodejs/npm-debug.log
```

**Comment by walkerdigital** [comment]
+1
